"""added rows in exam table

Revision ID: 6c57dd6f2dcf
Revises: c0e02236f666
Create Date: 2023-11-17 16:21:24.709891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c57dd6f2dcf'
down_revision: Union[str, None] = 'c0e02236f666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'certificates', ['id'])
    op.create_unique_constraint(None, 'divisions', ['id'])
    op.create_unique_constraint(None, 'employees', ['id'])
    op.create_unique_constraint(None, 'exams', ['id'])
    op.create_unique_constraint(None, 'examtypes', ['id'])
    op.create_unique_constraint(None, 'positions', ['id'])
    op.create_unique_constraint(None, 'subdivisions', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subdivisions', type_='unique')
    op.drop_constraint(None, 'positions', type_='unique')
    op.drop_constraint(None, 'examtypes', type_='unique')
    op.drop_constraint(None, 'exams', type_='unique')
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_constraint(None, 'divisions', type_='unique')
    op.drop_constraint(None, 'certificates', type_='unique')
    # ### end Alembic commands ###
