"""added rows in exam table x2

Revision ID: c1eb15da3af3
Revises: 6c57dd6f2dcf
Create Date: 2023-11-17 16:22:32.323460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1eb15da3af3'
down_revision: Union[str, None] = '6c57dd6f2dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('notation', sa.String(length=500), nullable=True))
    op.add_column('exams', sa.Column('place', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'place')
    op.drop_column('exams', 'notation')
    # ### end Alembic commands ###
